### ISSUE TITLE
Gaps in data series from PushProx clients when scrape interval > 5min

### ISSUE THREAD

**Issue by saulp** [RobustPerception/PushProx#56]
Hi all,

I've been chasing down an issue with gaps in my data series for the past few days, and I believe I've narrowed it down to scraping thru PushProx with an interval longer than 5m.

I'm attaching two screenshots showing the gap with the "up" metric, but the other metrics also show the gap. The scrape interval is 10m (which we cannot shorten, since we are collecting CPU-expensive metrics among other reasons.)

The tooltip text shows that the data seems to be quote-unquote "expired" after 5 minutes. I have tried the following to no avail:

* Downloaded the most recent proxy and client software
* Running the proxy software with flag "--registration.timeout=20m"

While I could work around this when visualizing with Grafana ("connect null values" does the trick nicely), the problem is that it affects alerting, as each gap seems to reset the alert period.

I wonder if this might have to do with the "WaitForScrapeInstruction" errors that I have been seeing in logs, which I'll log as a separate issue to keep things organized.

Thanks,
Saul

**Comment by saulp** [comment]
![pushprox-1614](https://user-images.githubusercontent.com/8971842/62735622-920f9200-b9f9-11e9-8fe2-e84be638ed6c.PNG)
![pushprox-1609](https://user-images.githubusercontent.com/8971842/62735623-920f9200-b9f9-11e9-9d0d-d25380edbb65.PNG)

**Comment by SuperQ** [comment]
This isn't a problem with PushProx, this is due to [staleness handling](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness) in Prometheus itself. Prometheus expects to have a scrape interval of no longer than 5 minutes. It's recommended to not have a scrape interval of longer than 2 minutes to avoid dropped samples causing staleness.

I recommend you increase the scrape interval to 2 minutes. This will not affect Prometheus storage, as it uses compression. Any scrape interval longer than 1 minute uses the same amount of space due to minimum samples per compressed block size limitations.

As a workaround, you can use `avg_over_time(metric[10m])` to make the query lookback over your scrape interval.

Remember, the gaps you see in the graph are actually your gaps in information. The resolution per data point in your graph is 14 seconds, yet you only have a data point every 600 seconds.

**Comment by saulp** [comment]
Thanks Ben. I appreciate the time you took to explain the reason as well as offer the avg_over_time suggestion, which I'll have to resort to since we have custom metrics that are expensive (cpu-wise) to generate and therefore we cannot scrape too often.

Cheers,
Saul

**Comment by SuperQ** [comment]
Prometheus design dictates that metric collection should always be cheap. There should not be CPU time involved to generate metrics. The standard design is to simply read existing data out of memory. It's likely that the exporter needs to be rewritten to meet the design assumptions. A typical exporter should gather data and respond within a few milliseconds.
